# Controller Main Configuration File.
author-msg: true
motd:
  server: "&1[&aCP &cServer Administration &6Working!&1]"
  ingame: "&chai"
  
# # Join messages.
Join:
  message: "&a&oJoin&8&l> &7%playername%"
  enabled: true
# # 
Quit:
  message: "&c&oQuit&8&l> &6%playername%"
  enabled: true
# # 
AlertPrefix: "&8&oAlert &b&l> &a&o"
# # 

# Disables TNT explosions:
Explosion:
  Disabled: true
# ======================================
#
#
# BCCPBR Block Restriction:
Blocks:
  message: '&c%player%, %6You do not have permission to use: '
  Restricted:
  - '7'
  - '8'
  - '9'
  - '10'
  - '11'
  - '119'
  - '259'
  - '51'
# ======================================
#
#
# Water and lava bucket restriction:
Bucket:
  WaterBucket:
    message: '&c%player%, &6You do not have permission to use: '
# #
kick-message: "&9Whitelist&8> &c&oConnection failed: &7You have not been whitelisted &a&o%playername%&c."
# ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ##
chat-disabled:
  msg: "&7The chat has been &cDisabled, &a %playername%"
### ### ### ###
Database:
  Enabled: false
  host: 10.0.0.1
  username: admin
  password: password
  database: database1
Table:
  logchat: true
  logcommands: true
  logplayer: true
restricted-msg: "&c&oYou have been &4&nRestricted &cand not allowed to &4Move&c."
restriction-msg: '&eUnknown command. Type "/help" for help.'
punish-command:
  Enabled: false
  function: "kick %player% &cDon't use that command."
blocked-cmds:
  - /pl
  - /plugins
  - /about
  - /bukkit
  - /?
  - /bukkit:help
  - /eessentials
custom-chat:
  Enabled: false
  Format: " &0[&6%username%&0] &7%message%"
Voting:
  Enabled: true
  broadcast: "&b[&6Vote&b] &e%playername% &avoted on &b%servicename%&c!"