name: Controller
main: com.enjin.es359.Controller
version: 2.1
description: Server Controller plugin. Supports MySQL function.
author: ES359

commands:
  alert:
    aliases: [a]
    description: Broadcasts a message across the server. 
    
  motd:
    description: Displays the currently set MOTDS.
    
  setmotd:
    description: Sets the ingame MOTD.
    
  setlistmotd:
    description: Sets the server List MOTD.
    
  cp:
    description: Defualt command for Control Panel.    
  
  kickmsg:
    description: Displays the whitelist message.
    
  setkickmsg:
    description: Sets the whitelist message.  
    
  usercp:
    description: Main command for USER CP. 
   
  chat:
    description: main command to enable or disable chat.

  restrict:
    aliases: [sr]
    description: Main command to Restrict a Player.

  permissions:
    aliases: [perms]
    description: Main command to display permissions.

  controller:
    description: Default command for Controller.

  sql:
    description: Command to execute SQL query's.

  addcmd:
    description: Main command for Controller Command restriction.
    aliases: [ac, addc, cadd,]

  auth:
    description: Author command.

  bugreport:
    description: Report command.

  reports:
    description: Main command for checking player reports.

  connection:
    description: Test and sql connection.
    aliases: [con]

  checkreports:
    description:
    aliases: [check]

  deletereport:
    description:
    aliases: [delete]

permissions:
  Controller.*:
    description: Gives access to all Controller permissions.
    default: op

  Controller.event.join:
    default: false
  Controller.event.quit:
    default: false